# VARIABLES
# ---------
title: plsmodeling
copyright: "Copyright 2012-2015, Gaston Sanchez."

# YEKYLL
# ------
highlighter: pygments

# must be redcarpet, for github style fenced code blocks (```r)
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:year/:month/:day/:title
